'use client';
import { useEffect, useMemo, useState } from 'react';
import './dashboard.css';

type Asset = 'BTC'|'ETH'|'SUI'|'BNB'|'XRP'|'SOL'|'LTC'|'ADA';
type Strategy = 'Bull Call Spread'|'Covered Call'|'Bear Put Spread'|'Iron Condor';
type Menu = 'Dashboard'|'Market'|'Positions'|'Strategies'|'Analytics'|'History'|'Watchlist';
const assets: Record<Asset, number> = { BTC:67842.36, ETH:3548.82, SUI:2.31, BNB:612, XRP:.58, SOL:154.7, LTC:87.5, ADA:.42 };
const menu: Menu[] = ['Dashboard','Market','Positions','Strategies','Analytics','History','Watchlist'];
const money = (value:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(value);
const today = '2026-09-04';

export default function Home() {
  const [page,setPage] = useState<Menu>('Dashboard');
  const [asset,setAsset] = useState<Asset>('BTC');
  const [strategy,setStrategy] = useState<Strategy>('Bull Call Spread');
  const [marketPrice,setMarketPrice] = useState(assets.BTC);
  useEffect(() => {
    setMarketPrice(assets[asset]);
    const timer = window.setInterval(() => setMarketPrice(previous => Number((previous * (1 + (Math.random()-.5)*.012)).toFixed(assets[asset] < 10 ? 4 : 2))), 2500);
    return () => clearInterval(timer);
  }, [asset]);
  return <main className="explorer"><Sidebar page={page} setPage={setPage}/>{page==='Dashboard'
    ? <Dashboard asset={asset} setAsset={setAsset} strategy={strategy} setStrategy={setStrategy} marketPrice={marketPrice}/>
    : <Detail page={page} asset={asset} price={marketPrice}/>}</main>;
}

function Dashboard({asset,setAsset,strategy,setStrategy,marketPrice}:{asset:Asset;setAsset:(v:Asset)=>void;strategy:Strategy;setStrategy:(v:Strategy)=>void;marketPrice:number}) {
  const [expiry,setExpiry] = useState('2026-09-30');
  const [mode,setMode] = useState<'Market price'|'Custom price'>('Market price');
  const [customPrice,setCustomPrice] = useState('');
  const invalidDate = expiry < today;
  const strike = Math.round(marketPrice * 1.02 / (marketPrice > 100 ? 10 : .1)) * (marketPrice > 100 ? 10 : .1);
  const premium = marketPrice * (strategy==='Covered Call'?.034:strategy==='Iron Condor'?.014:.027);
  const paths:Record<Strategy,string> = {
    'Bull Call Spread':'M15 194 L145 194 L252 130 L420 83 L535 83',
    'Covered Call':'M15 80 L145 80 L252 140 L420 194 L535 194',
    'Bear Put Spread':'M15 80 L145 80 L252 140 L420 194 L535 194',
    'Iron Condor':'M15 194 L130 194 L205 142 L345 142 L420 194 L535 194'
  };
  const path = paths[strategy];
  const points = path.match(/\d+/g)!.map(Number).reduce<number[][]>((all,v,i,values)=>i%2?[...all,[values[i-1],v]]:all,[]);
  const min = marketPrice*.6, max = marketPrice*1.3;
  const markerX = Math.max(15,Math.min(535,15+((marketPrice-min)/(max-min))*520));
  const end = points.slice(1).find((point,i)=>markerX<=point[0]&&markerX>=points[i][0]) || points[points.length-1];
  const index = points.indexOf(end), [startX,startY] = points[Math.max(0,index-1)];
  const markerY = startY + ((end[1]-startY)*(markerX-startX))/(end[0]-startX||1);
  const shownPrice = mode==='Market price' ? marketPrice : Number(customPrice||0);
  return <section className="content"><header className="top"><div><h1>Options Strategy Explorer</h1><p>Live {asset} option-market data from Thetanuts Protocol.</p></div></header>
    <section className="selector"><Field label="Strategy"><select value={strategy} onChange={e=>setStrategy(e.target.value as Strategy)}>{Object.keys(paths).map(name=><option key={name}>{name}</option>)}</select></Field><Field label="Asset"><select value={asset} onChange={e=>setAsset(e.target.value as Asset)}>{Object.keys(assets).map(name=><option key={name}>{name}</option>)}</select></Field>
    <div className="order-ticket"><Field label="Order price"><select value={mode} onChange={e=>setMode(e.target.value as 'Market price'|'Custom price')}><option>Market price</option><option>Custom price</option></select></Field><Field label={mode==='Market price'?'Latest market price':'Custom price'}><input type="number" value={mode==='Market price'?marketPrice:customPrice} readOnly={mode==='Market price'} onChange={e=>setCustomPrice(e.target.value)} step="any"/></Field><Field label="Expiry"><input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/>{invalidDate&&<small className="invalid">Invalid Date. Date must be today or later. Please choose again.</small>}</Field><div className="order-actions"><button className="sell" disabled={invalidDate}>Sell</button><button className="buy" disabled={invalidDate}>Buy</button></div></div>
    <div className="facts"><Fact label="Strike Price" value={money(strike)}/><Fact label="Premium" value={money(premium)}/><Fact label="Expiry" value={new Intl.DateTimeFormat('en-US',{day:'numeric',month:'short',year:'numeric'}).format(new Date(expiry+'T12:00:00'))}/><Fact label="Type" value="Call"/><Fact label="IV (30D)" value={(38+(marketPrice%12)).toFixed(2)+'%'}/></div></section>
    <section className="dash"><section className="payoff"><header><h2>Profit / Loss Payoff ⓘ</h2><button>At Expiry⌄</button></header><div className="legend"><span className="profit">━ Profit</span><span className="loss">━ Loss</span><span>━ Breakeven</span><span>┄ Strike Price</span></div><svg viewBox="0 0 550 245"><defs><clipPath id="profit"><rect width="550" height="121"/></clipPath><clipPath id="loss"><rect y="121" width="550" height="124"/></clipPath></defs><path className="grid" d="M35 20V222M135 20V222M235 20V222M335 20V222M435 20V222M535 20V222M35 20H535M35 70H535M35 121H535M35 171H535M35 222H535"/><path className="zero" d="M35 121H535"/><path className="strike" d="M335 20V222"/><path className="line profit-line" clipPath="url(#profit)" d={path}/><path className="line loss-line" clipPath="url(#loss)" d={path}/><circle className={'market-marker '+(markerY>121?'loss-marker':'')} cx={markerX} cy={markerY} r="5"><title>Latest {asset} price: {money(marketPrice)}</title></circle></svg><div className="axis"><span>{money(min)}</span><span>{money(marketPrice*.85)}</span><span>{money(marketPrice)}</span><span>{money(marketPrice*1.15)}</span><span>{money(max)}</span></div></section><aside className="right"><section><h2>Market Data</h2><p className="asset">◈ {asset} <small>/ USD</small></p><b className="price">{money(marketPrice)}</b><em>+1.28% (24h)</em></section><section><h2>Order preview</h2><p>{mode==='Market price'?'Latest price is used for this order.':'Custom price selected.'}</p><b>{shownPrice ? money(shownPrice) : 'Enter a custom price'}</b></section></aside></section></section>;
}
function Detail({page,asset,price}:{page:Menu;asset:Asset;price:number}){
  const title:Record<Exclude<Menu,'Dashboard'>,string>={Market:'Market overview',Positions:'Positions',Strategies:'Strategy scanner',Analytics:'Options analytics',History:'Activity history',Watchlist:'Watchlist'};
  const chart=<svg className="terminal-chart" viewBox="0 0 720 210" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#7c6cff" stopOpacity=".38"/><stop offset="1" stopColor="#7c6cff" stopOpacity="0"/></linearGradient></defs><path className="terminal-grid" d="M0 35H720M0 87H720M0 139H720M0 191H720M90 0V210M270 0V210M450 0V210M630 0V210"/><path fill="url(#area)" d="M0 160 L45 151 92 164 135 124 184 133 230 100 277 120 324 72 368 91 414 52 462 77 510 45 556 64 606 30 659 46 720 14 V210H0Z"/><path className="terminal-line" d="M0 160 L45 151 92 164 135 124 184 133 230 100 277 120 324 72 368 91 414 52 462 77 510 45 556 64 606 30 659 46 720 14"/></svg>;
  const stat=(label:string,value:string,delta:string,kind='positive')=><article className="terminal-stat"><span>{label}</span><b>{value}</b><small className={kind}>{delta}</small></article>;
  const section=(heading:string,children:React.ReactNode,action?:string)=><section className="terminal-panel"><header><div><h2>{heading}</h2><p>Updated moments ago</p></div>{action&&<button className="terminal-button">{action}</button>}</header>{children}</section>;
  const optionRows=[['27 Sep','65,000','Call','2,954','58.4%','+12.8%'],['27 Sep','70,000','Call','1,732','54.1%','+8.5%'],['4 Oct','70,000','Put','2,240','55.8%','−4.2%'],['4 Oct','75,000','Call','1,216','51.7%','+6.1%']];
  let body:React.ReactNode;
  if(page==='Market') body=<><div className="terminal-stats">{stat('Spot price',money(price),'+1.28% today')}{stat('24h volume','$24.8M','+18.6% vs avg')}{stat('Open interest','$86.4M','+4.2% today')}{stat('ATM IV','48.21%','−1.8 vol pts','neutral')}</div><div className="terminal-columns">{section(`${asset} / USD`,<><div className="chart-toolbar"><b>{money(price)}</b><span className="positive">● Live</span><div><button className="selected">1D</button><button>1W</button><button>1M</button></div></div>{chart}</>)}{section('Market pulse',<div className="pulse-list"><p><span>Put / Call ratio</span><b>0.74</b><em className="positive">Bullish</em></p><p><span>Max pain</span><b>$68,000</b><em>Near spot</em></p><p><span>Funding rate</span><b>0.011%</b><em className="positive">Positive</em></p><p><span>Skew (25Δ)</span><b>−2.8</b><em>Call bid</em></p></div>)}</div>{section('Most active contracts',<MarketTable rows={optionRows}/>, 'View chain')}</>;
  else if(page==='Positions') body=<><div className="terminal-stats">{stat('Portfolio value','$42,681.20','+$1,284.10 today')}{stat('Unrealized P&L','+$3,428.45','+8.74%','positive')}{stat('Portfolio delta','0.38','Moderate long','neutral')}{stat('Margin utilization','31.6%','Healthy','positive')}</div>{section('Open positions',<table className="terminal-table"><thead><tr><th>Strategy</th><th>Expiry</th><th>Contracts</th><th>Entry</th><th>Mark</th><th>P&L</th><th></th></tr></thead><tbody><tr><td><b>Bull call spread</b><small>BTC 65K / 70K</small></td><td>27 Sep 2026</td><td>2</td><td>$1,420.00</td><td>$1,716.20</td><td className="positive">+$592.40</td><td><button className="row-action">Manage</button></td></tr><tr><td><b>Cash-secured put</b><small>ETH 3.4K Put</small></td><td>4 Oct 2026</td><td>4</td><td>$184.00</td><td>$151.80</td><td className="positive">+$128.80</td><td><button className="row-action">Manage</button></td></tr><tr><td><b>Iron condor</b><small>BTC 60K / 76K</small></td><td>11 Oct 2026</td><td>1</td><td>$836.00</td><td>$782.75</td><td className="negative">−$53.25</td><td><button className="row-action">Manage</button></td></tr></tbody></table>,'New position')}<div className="terminal-columns lower">{section('Risk exposure',<RiskBars/>)}{section('Upcoming events',<div className="event-list"><p><b>27 Sep</b><span>BTC options expiry</span><em>$12.6K notional</em></p><p><b>4 Oct</b><span>ETH options expiry</span><em>$5.1K notional</em></p><p><b>11 Oct</b><span>BTC options expiry</span><em>$7.8K notional</em></p></div>)}</div></>;
  else if(page==='Strategies') body=<><div className="strategy-hero"><div><span className="eyebrow-terminal">DISCOVER TRADE IDEAS</span><h2>Find defined-risk opportunities</h2><p>Screen liquid option structures using live volatility, probability, and payoff metrics.</p></div><button className="primary-terminal">Build custom strategy</button></div><div className="strategy-filters"><button className="selected">All strategies</button><button>Income</button><button>Directional</button><button>Volatility</button><button>Hedging</button><select><option>BTC · All expiries</option></select></div><div className="strategy-cards"><StrategyCard title="Bull call spread" type="Directional" return="+42.8%" prob="58% probability" detail="Buy 65K Call · Sell 70K Call"/><StrategyCard title="Iron condor" type="Neutral income" return="+18.6%" prob="71% probability" detail="60K / 63K / 73K / 76K"/><StrategyCard title="Cash-secured put" type="Income" return="+12.4%" prob="76% probability" detail="Sell 62K Put · 23 DTE"/></div>{section('Scanner results',<MarketTable rows={optionRows}/>, 'Refine filters')}</>;
  else if(page==='Analytics') body=<><div className="terminal-stats">{stat('ATM implied volatility','48.21%','−1.8 pts today','neutral')}{stat('IV rank','64','Elevated regime','positive')}{stat('Expected move','$4,617','±6.82% to expiry','neutral')}{stat('Put / call volume','0.74','Calls leading','positive')}</div><div className="terminal-columns analytics-grid">{section('Implied volatility term structure',<><div className="vol-key"><span>● BTC ATM IV</span><span>— 30-day average</span></div><svg className="vol-chart" viewBox="0 0 480 200"><path className="terminal-grid" d="M20 30H460M20 80H460M20 130H460M20 180H460"/><path className="average-line" d="M30 75 L140 80 L250 91 L360 97 L450 102"/><path className="terminal-line" d="M30 118 L140 92 L250 61 L360 72 L450 55"/><circle cx="30" cy="118" r="5"/><circle cx="140" cy="92" r="5"/><circle cx="250" cy="61" r="5"/><circle cx="360" cy="72" r="5"/><circle cx="450" cy="55" r="5"/></svg><div className="axis-labels"><span>7D</span><span>14D</span><span>30D</span><span>60D</span><span>90D</span></div></>)}{section('Greeks snapshot',<RiskBars greeks/>)}</div>{section('Volatility surface',<div className="surface"><div className="surface-head"><span>Strike / Expiry</span><b>7D</b><b>14D</b><b>30D</b><b>60D</b></div>{['60K','65K','70K','75K','80K'].map((strike,i)=><div className="surface-row" key={strike}><span>{strike}</span>{[0,1,2,3].map(j=><b key={j} style={{opacity:.45+((i+j)%4)*.15}}>{(42+i*2+j*1.7).toFixed(1)}%</b>)}</div>)}</div>)}</>;
  else if(page==='History') body=<><div className="history-head"><div className="terminal-stats">{stat('Total realized P&L','+$8,294.60','Since inception')}{stat('Win rate','68.4%','13 of 19 closed')}{stat('Premium collected','$14,826.00','All time')}{stat('Avg. holding period','18 days','Disciplined')}</div></div>{section('Transaction history',<table className="terminal-table"><thead><tr><th>Date</th><th>Activity</th><th>Instrument</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody><tr><td>Sep 03, 14:32</td><td><b className="positive">Opened</b></td><td>BTC Bull Call Spread · Sep 27</td><td>−$2,840.00</td><td><span className="status open">Open</span></td><td>•••</td></tr><tr><td>Sep 01, 09:17</td><td><b className="positive">Closed</b></td><td>ETH Cash-Secured Put · Aug 30</td><td className="positive">+$736.00</td><td><span className="status settled">Settled</span></td><td>•••</td></tr><tr><td>Aug 29, 17:41</td><td><b className="negative">Expired</b></td><td>BTC Iron Condor · Aug 29</td><td className="positive">+$388.00</td><td><span className="status settled">Settled</span></td><td>•••</td></tr><tr><td>Aug 22, 11:06</td><td><b className="positive">Deposit</b></td><td>USDC collateral</td><td>+$10,000.00</td><td><span className="status settled">Confirmed</span></td><td>•••</td></tr></tbody></table>,'Export CSV')}</>;
  else body=<><div className="watchlist-top"><div><span className="eyebrow-terminal">YOUR MARKET RADAR</span><h2>Track the opportunities that matter.</h2></div><button className="primary-terminal">+ Add asset</button></div>{section('Saved assets',<table className="terminal-table watch-table"><thead><tr><th>Asset</th><th>Last price</th><th>24h</th><th>Implied vol.</th><th>Volume</th><th>Open interest</th><th>Signal</th><th></th></tr></thead><tbody>{[['BTC','67,842.36','+1.28%','48.21%','$24.8M','$86.4M','Call flow active'],['ETH','3,548.82','+2.14%','52.64%','$11.2M','$42.1M','IV expansion'],['SOL','154.70','−0.84%','67.10%','$4.8M','$13.7M','Watch support'],['BNB','612.00','+0.42%','44.36%','$1.6M','$7.9M','Range-bound']].map(row=><tr key={row[0]}><td><b className="coin">◈ {row[0]}</b><small>/ USD</small></td><td><b>${row[1]}</b></td><td className={row[2][0]==='+'?'positive':'negative'}>{row[2]}</td><td>{row[3]}</td><td>{row[4]}</td><td>{row[5]}</td><td><span className="signal">{row[6]}</span></td><td><button className="row-action">•••</button></td></tr>)}</tbody></table>)}</>;
  return <section className="content terminal-detail"><header className="top terminal-top"><div><span className="eyebrow-terminal">THETANUTS FINANCE · BASE MAINNET</span><h1>{title[page as Exclude<Menu,'Dashboard'>]}</h1><p>Professional options intelligence for your next decision.</p></div><div className="terminal-top-right"><span><i></i>Live data</span><button>BTC ▾</button></div></header>{body}</section>
}
function MarketTable({rows}:{rows:string[][]}){return <table className="terminal-table compact"><thead><tr><th>Expiry</th><th>Strike</th><th>Type</th><th>Premium</th><th>IV</th><th>24h change</th></tr></thead><tbody>{rows.map(row=><tr key={row.join('')}><td>{row[0]}</td><td><b>${row[1]}</b></td><td><span className={row[2]==='Call'?'call-tag':'put-tag'}>{row[2]}</span></td><td>${row[3]}</td><td>{row[4]}</td><td className={row[5][0]==='+'?'positive':'negative'}>{row[5]}</td></tr>)}</tbody></table>}
function RiskBars({greeks=false}:{greeks?:boolean}){const values=greeks?[['Delta','0.38',38],['Gamma','0.0048',24],['Theta','−$64.20',66],['Vega','$182.10',52]]:[['Delta exposure','Moderate long',62],['Theta decay','+$64.20 / day',72],['Vega exposure','Balanced',45],['Max loss at risk','$7,821',36]];return <div className="risk-bars">{values.map(([name,value,width])=><p key={name as string}><span>{name}</span><b>{value}</b><i><em style={{width:`${width}%`}}/></i></p>)}</div>}
function StrategyCard({title,type,return:yieldValue,prob,detail}:{title:string;type:string;return:string;prob:string;detail:string}){return <article className="strategy-card"><div><span>{type}</span><button>•••</button></div><h3>{title}</h3><p>{detail}</p><div className="strategy-metrics"><b>{yieldValue}<small>Max return</small></b><b>{prob}<small>Profit probability</small></b></div><button className="strategy-action">Analyze strategy →</button></article>}
function Sidebar({page,setPage}:{page:Menu;setPage:(x:Menu)=>void}){return <aside className="side" style={{display:'flex',flexDirection:'column',height:'100vh'}}><div className="logo"><img className="brand-mark" src="https://pbs.twimg.com/profile_images/1972581936314138624/MdNakWZA.jpg" alt="Thetanuts Finance"/><div><b>THETANUTS</b><small>Options Strategy Explorer</small></div></div><nav>{menu.map(item=><button key={item} className={page===item?'active':''} onClick={()=>setPage(item)}><i>▣</i>{item}</button>)}</nav><p className="base" style={{marginTop:'auto'}}>Built on<br/><strong>● BASE</strong></p></aside>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
function Fact({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
